name: Basic-Workflow/Pipeline

on:
  push:
    branches: [ main ]  # Pipeline/Workflow will run when there is a push to the main branch
  pull_request:
    branches: [ main ]  # Pipeline/Workflow will run when a Pull request is made to the main branch
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo Building
        run: echo "BUILDING"
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Make sure index.html exists
        run: cat index.html
        
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo Deploying
        run: echo "DEPLOYING"